export const Data = [{
    id: 0,
    Customer: "VirtualgoDown Tech Pvt LTD",
    ContractID: "MANA-2019-000001",
    WareHouse: "Olympic warehouse Pvt ltd - Olympic - Manali Uni1",
    TotalUnit: 10,
    StockValue: 64,
    StoragePlan: "Shared",
    CreatedAt: "12 - 12 - 12",
    Status: "Active",
    NetArea: null,
    GrossArea: null
  },
  {
    id: 1,
    Customer: "VirtualgoDown Tech Pvt LTD",
    ContractID: "MANA-2019-000001",
    WareHouse: "Olympic warehouse Pvt ltd - Olympic - Manali Uni1",
    TotalUnit: 10,
    StockValue: 64,
    StoragePlan: "Shared",
    CreatedAt: "12 - 12 - 12",
    Status: "Active",
    NetArea: null,
    GrossArea: null
  },
  {
    id: 2,
    Customer: "VirtualgoDown Tech Pvt LTD",
    ContractID: "MANA-2019-000001",
    WareHouse: "Olympic warehouse Pvt ltd - Olympic - Manali Uni1",
    TotalUnit: 10,
    StockValue: 64,
    StoragePlan: "Shared",
    CreatedAt: "12 - 12 - 12",
    Status: "Active",
    NetArea: null,
    GrossArea: null
  },
  {
    id: 3,
    Customer: "VirtualgoDown Tech Pvt LTD",
    ContractID: "MANA-2019-000001",
    WareHouse: "Olympic warehouse Pvt ltd - Olympic - Manali Uni1",
    TotalUnit: 10,
    StockValue: 64,
    StoragePlan: "Shared",
    CreatedAt: "12 - 12 - 12",
    Status: "Active",
    NetArea: null,
    GrossArea: null
  },
  {
    id: 4,
    Customer: "VirtualgoDown Tech Pvt LTD",
    ContractID: "MANA-2019-000001",
    WareHouse: "Olympic warehouse Pvt ltd - Olympic - Manali Uni1",
    TotalUnit: 10,
    StockValue: 64,
    StoragePlan: "Shared",
    CreatedAt: "12 - 12 - 12",
    Status: "Active",
    NetArea: null,
    GrossArea: null
  },
  {
    id: 5,
    Customer: "VirtualgoDown Tech Pvt LTD",
    ContractID: "MANA-2019-000001",
    WareHouse: "Olympic warehouse Pvt ltd - Olympic - Manali Uni1",
    TotalUnit: 10,
    StockValue: 64,
    StoragePlan: "Shared",
    CreatedAt: "12 - 12 - 12",
    Status: "Active",
    NetArea: null,
    GrossArea: null
  }
]
